openapi.yaml
views/index.html

1. update openapi.yaml
2. fix axios web version bug: header boundary not set default by the browser

fix: axios webboundary

---

readme.md
src/cmd/root.go
src/config/settings.go
src/go.mod
src/go.sum
src/main.go
src/services/app_service_impl.go
src/structs/send_struct.go
src/structs/user_struct.go
src/utils/whatsapp.go

- currently, we cannot change port and debug mode dynamically because it is hardcoded
1. Add Customizable port with `--port <number>`.
2. Add Customizable debug `--debug <true/false>`.
3. Add Auto reply command `--autoreply <string>` | when our device receives a message then this app is going to send an auto-reply with a custom message.

feat: add customable params

---

docs/openapi.yaml
readme.md
src/config/settings.go
src/controllers/send_controller.go
src/services/send_service.go
src/services/send_service_impl.go
src/structs/send_struct.go
src/validations/send_validation.go
src/views/index.html

- Adding send contact via API
- Adding UI for send contact
- Updating openapi

feat: add send contact

---

src/cmd/root.go
src/config/settings.go

Adding basic auth params when start app
`./main --basic-auth=aldinokema:secret`
or
`./main -b=aldinokema:secret`

feat: add basic auth in params

---

readme.md
src/cmd/root.go
src/config/settings.go
src/utils/whatsapp.go

- Add webhook for every received message

feat: add new webhook endpoint

---

.gitignore
readme.md
src/cmd/root.go
src/config/settings.go
src/utils/whatsapp.go

- Currently is hard to update the version without relogin, so we need to create one folder to save all data. Furthermore, this will make it easily binding volume with the docker

feat: move file to storage folder

---

readme.md
src/cmd/root.go

- Some of you probably would like to **change** the app name with **your application name**, now you can do this with simple command `--os=MyApplication`

feat: allow to change os name

---

docs/openapi.yaml
readme.md
src/cmd/root.go
src/config/settings.go
src/domains/app/devices.go
src/domains/send/contact.go
src/domains/send/file.go
src/domains/send/image.go
src/domains/send/link.go
src/domains/send/message.go
src/domains/send/send.go
src/domains/send/text.go
src/domains/send/video.go
src/internal/rest/app_rest.go
src/internal/rest/send_rest.go
src/internal/rest/user_rest.go
src/internal/websocket/websocket.go
src/services/app_service.go
src/utils/errors.go
src/utils/response.go
src/utils/whatsapp.go
src/validations/send_validation.go
src/validations/send_validation_test.go
src/validations/user_validation.go
src/views/index.html

- change API send message (make send group & direct message without type)
- add WebSocket to detect login
- update docs

feat: redesign UI 4.0

---

docs/openapi.yaml
readme.md
src/config/settings.go
src/domains/send/location.go
src/domains/send/send.go
src/internal/rest/send.go
src/pkg/utils/general.go
src/pkg/whatsapp/whatsapp.go
src/services/app.go
src/services/send.go
src/services/user.go
src/validations/send_validation.go
src/validations/send_validation_test.go
src/validations/user_validation.go
src/validations/user_validation_test.go
src/views/index.html

- Add a feature to send locations with latitude and longitude
- Fix removed files whether logout
- Add context in every validation

feat: add send location

---

src/domains/send/file.go
src/services/send.go

feat: add send file caption

---

docs/openapi.yaml
src/cmd/root.go
src/config/settings.go
src/domains/message/message.go
src/domains/message/reaction.go
src/domains/message/revoke.go
src/domains/message/update.go
src/domains/send/reaction.go
src/domains/send/send.go
src/go.mod
src/go.sum
src/internal/rest/message.go
src/internal/rest/send.go
src/services/message.go
src/services/send.go
src/validations/message_validation.go
src/validations/send_validation.go
src/views/index.html

feat: add reaction

---

readme.md
src/cmd/root.go
src/domains/group/group.go
src/internal/rest/group.go
src/services/group.go

First of all, thanks for this great project, it was exactly what I was looking for!
I know very little of go. Almost nothing actually, but I wanted to add functionality to join a group with a link. This is exactly what I did in this pull request. 
I have no clue about testing or other pull request hygiene for this project, so let me know if you're interested in this change, and if you are, what should happen to make it ok for consumption.

feat: Add Join Group with Link

---

src/go.mod
src/pkg/whatsapp/whatsapp.go

in continue to issue: #81 
add condition, if message received with ExtendedTextMessage, then use it, else use Conversation attribute

add condition, if message received with ExtendedTextMessage, then use it, else use Conversation attribute

---

docs/openapi.yaml
src/cmd/root.go
src/config/settings.go
src/domains/app/app.go
src/domains/app/devices.go
src/domains/app/login.go
src/domains/send/text.go
src/go.mod
src/services/app.go
src/services/send.go
src/views/index.html

- Add reply message via text, by adding parameter `reply_message_id` (optional), check `docs/openapi.yaml` for detail
- Update openapi.yaml

feat: add reply message

---

src/pkg/whatsapp/whatsapp.go

fix: verify context nil error on extMsg

---

readme.md
src/config/settings.go
src/domains/group/group.go
src/internal/rest/group.go
src/pkg/error/whatsapp_error.go
src/pkg/whatsapp/whatsapp.go
src/services/group.go
src/validations/group_validation.go
src/views/components/GroupCreate.js
src/views/components/GroupJoinWithLink.js
src/views/components/GroupList.js
src/views/index.html

- Add api create group
- Add ui create group
- add ui join group with link

feat: create and join group

---

src/cmd/root.go
src/config/settings.go
src/internal/rest/middleware/basicauth.go
src/pkg/error/app_error.go
src/pkg/whatsapp/whatsapp.go
src/services/message.go
src/services/send.go
src/services/user.go

- Removing unused code
- Lintint golang code

feat: optimize code

---

src/views/components/SendMessage.js

- Fix invalid payload after refactor UI

fix: reply from UI

---

docs/openapi.yaml
readme.md
src/config/settings.go
src/domains/message/message.go
src/go.mod
src/go.sum
src/internal/rest/message.go
src/services/message.go
src/validations/message_validation.go
src/views/components/GroupManageParticipants.js

- Add new API for mark message as read in Direct Message
- POST /message/:message_id/read

feat: mark as read

---

docs/openapi.yaml
src/config/settings.go
src/domains/send/audio.go
src/domains/send/image.go
src/go.mod
src/go.sum
src/internal/rest/send.go
src/pkg/utils/general.go
src/pkg/utils/general_test.go
src/services/send.go
src/validations/send_validation.go
src/validations/send_validation_test.go
src/views/components/SendImage.js

- Now we can send image via URL, just paste URL in `image_url`

feat: send image from URL

---

src/views/components/MessageRead.js
src/views/index.html

- Added MessageRead component with UI for marking WhatsApp messages as read
- Integrated component into main index.html page
- Enables users to mark specific messages as read through the web interface

feat(message): add UI component to mark messages as read

---

src/.env.example
src/cmd/root.go
src/config/settings.go
src/infrastructure/whatsapp/init.go

Reverts aldinokemal/go-whatsapp-web-multidevice#254

Revert "fix: large groups bypass with in-memory storage of the keys"

---

docs/webhook-payload.md
src/infrastructure/whatsapp/init.go
src/views/components/ChatList.js
src/views/components/ChatMessages.js
src/views/index.html

- Added new chat list UI component with search, pagination, and filtering capabilities
- Added chat messages viewer component with advanced filtering options
- Improved auto-reply functionality with proper context handling and message storage
- Enhanced webhook payload documentation with better formatting and JID examples
- **Chat List Component (`src/views/components/ChatList.js`)**:
- Interactive chat list with search functionality
- Pagination support for large chat lists
- Media chat filtering option
- Integration with chat messages viewer
- **Chat Messages Component (`src/views/components/ChatMessages.js`)**:
- Advanced message filtering (by content, sender, date range, media type)
- Paginated message display with proper formatting
- Support for both individual and group chats
- …

feat: add chat list and messages UI components with auto-reply improvements
